# ONLY FOR DEV
version: "3.9"
services:
  db:
    image: postgres
    env_file:
      - ./postgres.env
    build:
      context: ..
      dockerfile: ./dev/database.Dockerfile
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./pgadmin.env
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin
  server:
    build:
      context: ..
      dockerfile: ./dev/server.Dockerfile
    depends_on:
      - db
    ports:
      - 3001:80
    volumes:
      - ../app:/code/app
    environment:
      - JAEGER_SERVICE_NAME=moviedb
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831     
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
  redis:
    container_name: "redis"
    image: redis:alpine
    ports:
      - 6379:6379 
  jaeger: 
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
  
volumes:
  pg_data:
  pgadmin:
